"""Export a trained AccelToVelGRU checkpoint (gru_imu_model.pth) into files
MicroPython can load on the Pico, with no torch/numpy dependency on-device:

  - weights.bin       raw float32 weights, in a fixed order (see model.py)
  - weights_meta.py   plain-Python module with the small hyperparameters
                      (input/hidden/output size, num_layers, window_size)

Run this on your PC (same env you trained in). It does NOT run on the Pico.
"""
import struct
import torch

CKPT_PATH = "gru_imu_model.pth"
BIN_PATH = "weights.bin"
META_PATH = "weights_meta.py"


def flat(t):
    return t.detach().cpu().numpy().astype("float32").flatten().tolist()


def main():
    ckpt = torch.load(CKPT_PATH, map_location="cpu")
    sd = ckpt["model_state_dict"]
    input_size = ckpt["input_size"]
    hidden_size = ckpt["hidden_size"]
    num_layers = ckpt["num_layers"]
    output_size = ckpt["output_size"]
    window_size = ckpt["window_size"]

    tensors = []
    for l in range(num_layers):
        tensors.append(flat(sd[f"gru.weight_ih_l{l}"]))
        tensors.append(flat(sd[f"gru.weight_hh_l{l}"]))
        tensors.append(flat(sd[f"gru.bias_ih_l{l}"]))
        tensors.append(flat(sd[f"gru.bias_hh_l{l}"]))
    tensors.append(flat(sd["fc.weight"]))
    tensors.append(flat(sd["fc.bias"]))

    all_values = [v for t in tensors for v in t]

    with open(BIN_PATH, "wb") as f:
        f.write(struct.pack("<%df" % len(all_values), *all_values))

    with open(META_PATH, "w") as f:
        f.write("# Auto-generated by export_to_micropython.py - do not edit by hand\n")
        f.write(f"INPUT_SIZE = {input_size}\n")
        f.write(f"HIDDEN_SIZE = {hidden_size}\n")
        f.write(f"NUM_LAYERS = {num_layers}\n")
        f.write(f"OUTPUT_SIZE = {output_size}\n")
        f.write(f"WINDOW_SIZE = {window_size}\n")

    total_bytes = len(all_values) * 4
    print(f"Wrote {BIN_PATH} ({total_bytes} bytes, {len(all_values)} floats)")
    print(f"Wrote {META_PATH}")
    print(
        f"input_size={input_size} hidden_size={hidden_size} "
        f"num_layers={num_layers} output_size={output_size} window_size={window_size}"
    )
    print(
        f"\nEstimated on-device RAM for weights alone: ~{total_bytes // 1024} KB "
        f"(Pico has 264 KB total SRAM shared with the MicroPython runtime)."
    )


if __name__ == "__main__":
    main()
